{% set version = "0.87" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-corrplot
  version: {{ version|replace("-", "_") }}

source:
  fn: corrplot_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/corrplot_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/corrplot/corrplot_{{ version }}.tar.gz
  sha256: b251a2130aa4f9730dd723b732c9daf2915a9d186a6be7051aabe88f1b69f2b6

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('corrplot')"  # [not win]
    - "\"%R%\" -e \"library('corrplot')\""  # [win]

about:
  home: https://github.com/taiyun/corrplot
  license: GPL
  summary: A graphical display of a correlation matrix or general matrix. It also contains some algorithms to do matrix reordering.
  license_family: GPL

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
