travis:
  secure:
    BINSTAR_TOKEN: NvnqVunlz3o7IqcK7AAt6FVfCyulShf8nZTvqP86TiXHCZRFl018rBEP/gaZBV8rJIjSTJeVpu8+0WoMaD8S/5MDLPS3W/w8qWBgpdO4fmFb19x9akOh1LuvJIb8SN8JPbVJb3BfmlQ/86BM+bwl1NIFJuGGw/qk+3j9DLifeq0uZEEIrwbQ7u8iGc2+rS2UdqlKSVUlChh0ogmQUqB9aEZp6xnxG7bok3E7HvetXVNjkxjkBM6KhJip2ScN9r+2Cxzryq8EAMrNL3cY/PqFgiLwwyVA9m+ufL+xtMQ9FIt9HaNXF5M4EErCnKM/ZgyGGC0VlQElFWUbKrO63f1FacdtZKueh9I0Zx8d2WjBhokQJgbL2ei0dHxpxh82JcOjzdKmRfFENx+h++Xmwix2FxYuI1agVzYuAN6Sk78QBSOAtJbIDLX1eLZ/qZAAdVpvCCc6h8iukZAZrb9Rj4j6AtzJIwTYIubu36T4vEKzaJO/S3NzXPQExZjDYOWrzUcuXtYfwQ/ZKVKnNGkvAlR9qgFU07XjnWRBeloSWBbKIFLIRjQBEAdGrAae6dRRgb7cM0FezR8pzzBNAe4EeIrsaMfaoBvJDkhltdZCfW5SOCto/Sizt7UzbrSZiV9JI5vOD70sT3fjaJQ2vrJfu3OPGCZNg9V14GBwRSzPnUNcZYM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
