travis:
  secure:
    BINSTAR_TOKEN: x8kAkYyxKLEsCpZwySQOHK/azXn5mgn6dxzoTZyJ2Dj8e0VdsF1AFLwPuqlrc5xNV2k2cwWyjirO5MYm3WvxfwnKLc2ueTa0xhzctybmWIuMiqKYp8St9QLvaNQ+Yif4fu9CvuPDb9Er9SCWrgAES8hmeNtSwO5Q4nn9TEkvb5aB9B9+6bh+GDpKeBOSyCe+cm3un2b2yJuhJPqUzbzDLLHGyRpqCivAd/BN/eIcigdyVHu84YqzXwCZD7B8nlMRA3HBghSr4JGskIEcQxgHDbCP3TKLYo2PPmtuE923wOWzuH0MPuYuT+mbe6CdDtsYUR3d/yZPxaI29c3AZa9eVvJBlBtEp9wk4Ws31+V3och38c/Q2uB2bH1JJJqE16iCkwRYrGrChMQow+zJzjP0xbBUirAEnpuBNPD6nbo4cI8NfhGvtOY7kq1h647QD6WJM1ppci/aBWWg6wLdXrwBloD0GDzlwMUxabxjS+X40lFgpiPRiWCXAWtd3G6sc1c/g5s/p87vs9Yado9Gkm0iU5r9pyU1rwAbYYCYafx+bEgCnsHAYAmLQQx7YHw0u6BSziYndl+oO5irDmH3UGIdfLB+mB6CJvvaA8HTdINt7KK6k7swhwYsQBgDF7aJ43+3I0RwLweMxmADXdpI5u86Vv/JilGaVVMBX9oRZwwn4W0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
